# Generated by Django 2.1.5 on 2019-01-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fupdate',
            name='updatecode',
            field=models.IntegerField(default=-1),
        ),
    ]
